# Generated by Django 5.1.1 on 2024-09-04 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_alter_employee_card_creation_address_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_card_creation',
            name='age',
        ),
        migrations.AddField(
            model_name='employee_card_creation',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
