# Generated by Django 5.1.1 on 2024-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_remove_employee_card_creation_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_card_creation',
            name='father_name',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='employee_card_creation',
            name='mother_name',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='employee_card_creation',
            name='nationality',
            field=models.CharField(choices=[('BRA', 'Brasileira'), ('ARG', 'Argentina'), ('URU', 'Uruguaia'), ('PAR', 'Paraguaia'), ('VEN', 'Venezuelana'), ('COL', 'Colombiana'), ('PER', 'Peruana'), ('CHI', 'Chilena'), ('EQU', 'Equatoriana'), ('BOL', 'Boliviana'), ('EUA', 'Americana'), ('POR', 'Portuguesa'), ('ESP', 'Espanhola'), ('FRA', 'Francesa'), ('ITA', 'Italiana'), ('ALE', 'Alemã'), ('ING', 'Inglesa')], default='Brasileira', max_length=100),
        ),
        migrations.AddField(
            model_name='employee_card_creation',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_card_creation',
            name='marital_status',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20),
        ),
    ]
